dbtdemo:
  target: dev
  outputs:
    dev:
      type: mysql
      server: 192.168.1.179
      port: 3306
      database: airbytepoc
      schema: airbytepoc
      username: root
      password: akash
      ssl_disabled: True
    # prod:
    #   type: mysql
    #   server: [server/host]
    #   port: [port]  # optional
    #   database: [schema] # optional, should be same as schema
    #   schema: [schema]
    #   username: [username]
    #   password: [password]
    #   driver: MySQL ODBC 8.0 ANSI Driver
